include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_single_quotes: true
    always_use_package_imports: true
    
    # Error rules
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    prefer_typing_uninitialized_variables: true
    
    # Documentation
    public_member_api_docs: false

analyzer:
  exclude:
    - "example/**"
    - "test/**" 